version: '2.0'
services:
    derp :
        container_name: ${DOCKER_SERVICE} 
        restart: always
        ports:
            - '3478:3478/udp'
            - '12345:12345'
        volumes:
            - '../certs:/cert'
            - '/var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock'
        image: fredliang/derper
        environment:
            - DERP_DOMAIN=${HOST_NAME}
            - DERP_ADDR=:12345
            - DERP_STUN=true
            - DERP_STUN_PORT=3478
            - DERP_CERT_MODE=manual
            - DERP_CERT_DIR=/cert
            - DERP_VERIFY_CLIENTS=true
